# Generated by Django 2.2.17 on 2020-12-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hgjhg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhgfhgf',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userhgfhgf',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userhgfhgf',
            name='password',
        ),
    ]
